name: IRIS CI Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      # 4. Install Python dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install "dvc[gdrive]" pytest==7.4.4 



      # 6. Pull DVC data & model
      - name: Pull DVC Data & Model
        run: dvc pull

      # 7. Run tests (Fetch model from MLflow)
      - name: Run Test Pipeline (Using MLflow Registry)
        env:
          MLFLOW_TRACKING_URI: http://34.70.222.183:8100
        run: |
          echo "Starting sanity tests using model from MLflow Model Registry"
          pytest tests/test_pipeline.py -v
      # 7. Setup iterative CML
      - name: Setup CML
        uses: iterative/setup-cml@v2

      # 8. Generate and Post CML Report 
      - name: Generate and Post CML Report
        if: github.event_name == 'pull_request'
        env:
          REPO_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # Create report
          echo "**********Test Results********" > report.md
          echo "" >> report.md
          cat metrics_test.csv >> report.md
          # Post PR comment
          cml comment create report.md
